### ISSUE TITLE
Was exporting 2 arc of STGGanonTower by Mewtwo2000 on Brawl Vault

### ISSUE THREAD

**Issue by StageBoxBrawl** [StageBoxBrawl/StageBoxIssues#17]
Was exporting all as dae and png from the 2 arc file of STGGanonTower

BrawlCrate_v0.15
Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at BrawlLib.Modeling.Collada.WriteNormals(String name, XmlWriter writer, PrimitiveManager p)
   at BrawlLib.Modeling.Collada.WriteGeometry(MDL0Node model, XmlWriter writer)
   at BrawlLib.Modeling.Collada.Serialize(MDL0Node model, String outFile)
   at BrawlLib.SSBB.ResourceNodes.MDL0Node.Export(String outPath)
   at BrawlLib.SSBB.ResourceNodes.BRRESNode.ExportToFolder(String outFolder, String imageExtension, String modelExtension)
   at BrawlLib.SSBB.ResourceNodes.ARCNode.ExtractToFolder(String outFolder, String imageExtension, String modelExtension)
   at BrawlCrate.ARCWrapper.ExportAll()
   at BrawlCrate.ARCWrapper.ExportAllAction(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by soopercool101** [comment]
Fixed in https://github.com/soopercool101/BrawlCrate/commit/c297da0f99f318aa06138fcb29586a6c0560f7e0
